environment:
    rustversion: 1.67.0
    matrix:
            - platform: x86_64
              rusthash: 57785F84901A45BF5168A9EB3451AD9E5BA1A9F0C7A928916879A21EE97A6706
            - platform: i686
              rusthash: AD12F16615CD31A787247174B6FE0BD3607C6C7063992C2F9101736CCCAA1B04
install:
# Need Mingw to build C bits
- SET PATH=%PATH%;C:\MinGW\bin
- ps: Start-FileDownload https://static.rust-lang.org/dist/rust-$env:RUSTVERSION-$env:PLATFORM-pc-windows-msvc.msi -FileName rust.msi
- ps: |
        $h = (Get-FileHash rust.msi).Hash
        echo $h
        if ($h -ne $env:rusthash) {
                throw "Hash mismatch while downloading Rust"
        }
- msiexec /passive /i rust.msi ADDLOCAL=Rustc,Cargo,Std INSTALLDIR=C:\Rust
- start /wait msiexec /i rust.msi INSTALLDIR="C:\Program Files\Rust" /quiet /qn /norestart /log install.log
- SET PATH=%PATH%;C:\Rust\bin
- rustc -vV
- cargo -V
- set RUST_BACKTRACE=1
matrix:
  fast_finish: true
build_script:
- contrib\appveyor-build.bat
after_build:
- contrib\appveyor-after-build.bat
test_script:
- contrib\appveyor-test.bat
artifacts:
- path: '*.zip'
deploy:
  - provider: GitHub
    description: Automated builds (Appveyor)
    release: $(appveyor_repo_tag_name)
    auth_token:
      secure: EC3hRzfCyV2DwNDMFWvk1cfV/0cKjW60Jb1C0VP4sCT5j2ePf22h5XVEzpSmsvRcF/LBbniN8Y/AUgHBVg9uSogM0ioX9mdFurMRKG2hlOGN85NZLziCAojQs/5ZCYC6
    artifact: /.*\.zip/ 
    prerelease: false
    on:
      appveyor_repo_tag: true
